version : '3'
services :
    smart-auth:
        build: ./docker/auth/
        ports:
            - 9000:3000
        depends_on:
            - smart-doctrina
        volumes:
            - ./smart-auth/:/usr/src/app
    smart-doctrina:
        build:  ./docker/doctrina/
        ports:
            - 9001:80
        depends_on:
            - db
        volumes: 
            - ./docker/doctrina/:/etc/apache2/sites-enabled
            - ./smart-doctrina/:/var/www/
    db:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD : 'root'
            MYSQL_DATABASE: 'root'
        ports:
            - 3306:3306
        volumes:
            - ./db_data:/var/lib/mysql